org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=false
org.gradle.vfs.watch=false
android.enableJetifier=false
android.useAndroidX=true
android.builtInKotlin=false
android.newDsl=false
kotlin.incremental=false